// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ridalot2._0.Data.RIDALOT
{
    public partial class Posts
    {
        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public int? Status { get; set; }
        public string User { get; set; }
        public byte[] Image { get; set; }
        public string Description { get; set; }
        public int? Height { get; set; }
        public int? Width { get; set; }
        public int? Length { get; set; }
        public int? Weight { get; set; }
        public string Address { get; set; }
        public double? Pay { get; set; }
        public string Worker { get; set; }
    }
}