// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ridalot2._0.Data.RIDALOT
{
    public partial class Posts
    {
        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public Status? Status { get; set; }
        public string User { get; set; }
        public virtual ICollection<Images> Images { get; set; }
        public string Description { get; set; }
        public int? Height { get; set; }
        public int? Width { get; set; }
        public int? Length { get; set; }
        public int? Weight { get; set; }
        public double AddressLat { get; set; }
        public double AddressLng { get; set; }
        public int? Floor { get; set; }
        public double? Pay { get; set; }
        public string Worker { get; set; }
    }
}